### ISSUE TITLE
404 on eCloud Flex searches

### ISSUE THREAD

**Issue by alegradi** [ans-group/docs.ukfast.co.uk#665] opened 2020-07-22 09:38 UTC
The documentation at:
- https://docs.ukfast.co.uk/ecloud/flex/res/compute/flavours.html 
- https://docs.ukfast.co.uk/ecloud/flex/res/orchestration/magnum.html
etc...

Currently only returns a 404. These URL are results of using the search function.

If you navigate to it through the menus the page is displayed correctly:
- https://docs.ukfast.co.uk/ecloud/flex/resources/compute/flavours.html
- https://docs.ukfast.co.uk/ecloud/flex/resources/orchestration/magnum.html
etc...

As you can see the URL changes from `flex/resources/page` to `flex/res/pages` when doing a search.

**Comment by miff2000** [comment] 2020-07-22 11:07
I believe this is caused by the search and replace we do for the word `source` from the URL.  Seems to be turning

* `resources` -> `res`

Sound about right @darrentayloruk ?

**Comment by darrentayloruk** [comment] 2020-07-22 13:03
Correct... having fixed once on the ES populator.. it seems theres a JS replace too!!!

found it.... simple fix will push now

**Closed as completed** 2020-07-22 13:25 UTC
